### ISSUE TITLE
Cant acces the game

### ISSUE THREAD

**Issue by haltia** [HikariKnight/rsu-client#100]
@HikariKnight The client launcher launches normally execpt when i press play now nothing happens.

**Comment by haltia** [comment]
Im getting this when i try to start oldschool runescape.

**Comment by haltia** [comment]
WARNING: List::MoreUtils module not found on the system,
using the version provided by the client instead!

Unknown named parameter -fallback=>_ at /opt/runescape/rsu/framework/modules/rsu/files/IO.pm line 203
Can't call method "val" on an undefined value at /opt/runescape/rsu/framework/modules/rsu/files/IO.pm line 206.
Compilation failed in require at (eval 37) line 2.
BEGIN failed--compilation aborted at (eval 37) line 2.
	...caught at /opt/runescape/rsu/apiquery.pm line 46.

**Comment by haltia** [comment]
@HikariKnight

**Comment by jamesm32** [comment]
Not sure if this is exactly the same issue but it has similarities so could be:

I too can load the client but when pressing Play Now the game doesn't load. This is the output when loaded from the terminal:

Exception in thread "main" java.lang.NullPointerException
	at sun.font.FontManager.getDefaultPlatformFont(FontManager.java:3409)
	at sun.java2d.SunGraphicsEnvironment$2.run(SunGraphicsEnvironment.java:263)
	at java.security.AccessController.doPrivileged(Native Method)
	at sun.java2d.SunGraphicsEnvironment.<init>(SunGraphicsEnvironment.java:164)
	at sun.awt.X11GraphicsEnvironment.<init>(X11GraphicsEnvironment.java:254)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:57)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:534)
	at java.lang.Class.newInstance(Class.java:379)
	at java.awt.GraphicsEnvironment.getLocalGraphicsEnvironment(GraphicsEnvironment.java:82)
	at java.awt.Window.init(Window.java:495)
	at java.awt.Window.<init>(Window.java:548)
	at java.awt.Frame.<init>(Frame.java:419)
	at java.awt.Frame.<init>(Frame.java:384)
	at app.appletviewer.a(appletviewer.java:507)
	at jagexappletviewer.main(jagexappletviewer.java:34)

**Comment by jamesm32** [comment]
PS I'm running on Trisquel 7, very similar to Ubuntu 14.10

**Comment by jamesm32** [comment]
@HikariKnight

**Comment by HikariKnight** [comment]
@haltia
Sorry I'm in the middle of moving and have no internet currently so I can't check much. But I think you might be missing (or have a corrupt or outdated) 
Config::Inifile
In perl, check if you have a newer one on your system.

**Comment by HikariKnight** [comment]
@jamesm32
Never heard about your distro, but what I can see from the Java errors, it is struggling to find X11 (the x window system) or you might be running a headless java implementation (CLI only java)

**Comment by jamesm32** [comment]
Hey, you're right, installing openjdk properly fixed it for me, thanks!

**Comment by HikariKnight** [comment]
no reply from original poster for over a month, closing this
