### ISSUE TITLE
File not found ~/.config/runescape/share/cache/jagexappletviewer.preferences 

### ISSUE THREAD

**Issue by bayanr** [HikariKnight/rsu-client#64]
When trying to launch the game, the following exception is thrown:

java.io.FileNotFoundException: ~/.config/runescape/share/cache/jagexappletviewer.preferences (No such file or directory)
	at java.io.FileOutputStream.open(Native Method)
	at java.io.FileOutputStream.<init>(FileOutputStream.java:221)
	at java.io.FileOutputStream.<init>(FileOutputStream.java:171)
	at app.m.b(m.java:53)
	at app.appletviewer.a(appletviewer.java:501)
	at jagexappletviewer.main(jagexappletviewer.java:34)
Exception in thread "main" java.awt.HeadlessException
	at java.awt.GraphicsEnvironment.checkHeadless(GraphicsEnvironment.java:207)
	at java.awt.Window.<init>(Window.java:535)
	at java.awt.Frame.<init>(Frame.java:420)
	at java.awt.Frame.<init>(Frame.java:385)
	at app.appletviewer.a(appletviewer.java:507)
	at jagexappletviewer.main(jagexappletviewer.java:34)

Where can I get this file?

@HikariKnight

**Comment by bayanr** [comment]
Issue solved. Just run the following command:

touch ~/.config/runescape/share/cache/jagexappletviewer.preferences

**Comment by HikariKnight** [comment]
hmm curious to why it did not create that folder to begin with.

**Comment by bayanr** [comment]
Most likely it is a bug in the client. I think the file should be created
by the RSU launcher just in case since the rs client doesn't seem to mind
if it's there.
